### ISSUE TITLE
Bootstrap React-native front-end Soog project

### ISSUE THREAD

**Issue by younesdiouri** [Soog-app/front#1]
## Tasks : 

- [x]  init project on git 
- [x]  create homepage view
- [x] create singup view
- [x]  create signin view
- [x] automatic login
- [x] logout
- [x]  create logged in view (just the route and a blank template)
